# Site settings
title: Julien Mariette
email: info@julienmariette.be
description: > # this means to ignore newlines until "baseurl:"
baseurl: "/jmariette-project1/" # the subpath of your site, e.g. /blog/
url: "https://laberomain.github.io" # the base hostname & protocol for your site

twitter_username:
github_username:

# Build settings
markdown: kramdown
